name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # with:
        #   token: ${{ secrets.ACTION_GITHUB_TOKEN }}
        #   fetch-depth: 0
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Build project
        # run only on push events
        if: github.event_name == 'push'
        run: npm run build
        # install surge
      # - run: npm install -g surge
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: npx sugre --project ./build --domain my-pipeline-ci-cd.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
