name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          node-version: "19.x"
          cache: "npm"
          # path: ~/.npm
          # key: ${{ runner.os }}-node-{{ hashFiles('**/package-lock.json')}}
          # restore-keys: |
          #   ${{ runner.os }}-node-

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "19.x"
      - run: npm install
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: coverage
      - name: Build project
        # run only on push events
        if: github.event_name == 'push'
        run: npm run build
      - name: Upload Build folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
      - name: Deploy to Staging
        if:
          github.event_name == 'push'
          # install and run surge
        run: npx surge --project ./build --domain my-pipeline-ci-cd.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
